### ISSUE TITLE
How to check if connection still alive?

### ISSUE THREAD

**Issue by bubnenkoff** [salim-lachdhaf/ftpConnect#45]
I faced with situation where server is closing connection before I am starting downloading, so I am getting FTPException, that file does not exist. But it's exists, just connection is closed.

How to check if it alive and reopen if needed?

```
FTP Exception: Remote File /fcs_regions/Sankt-Peterburg/notifications/notification_Sankt-Peterburg_2021070100_2021080100_011.xml.zip does not exist! Second Attempt to download file
2022-01-14 12:15:41.993429 - error - FTPException: Timeout reached for Receiving response ! (Response: n
ull)
2022-01-14 12:15:41.993429 - error - #0      FTPSocket.readResponse.<anonymous closure> (package:ftpconn
ect/src/ftpSocket.dart:38:7)
#1      _RootZone.run (dart:async/zone.dart:1681:54)
#2      Future.timeout.<anonymous closure> (dart:async/future_impl.dart:865:34)
#3      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#4      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:395:19)#5      _Timer._handleMessage (dart:isolate-patch/ti
mer_impl.dart:426:5)
#6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
```

on follow code:
```
try {
  await ftpConnect.downloadFileWithRetry(ftpArchiveFullPath, File(localArchiveFullPath), pRetryCount: 2);

} on FTPException catch (e) { //
  print(e);  
  print("${ftpArchiveFullPath}");
  print('FTP Exception: ${e.message} Second Attempt to download file'); 
  await ftpConnect.connect(); // possible connection was closed? 
  print("recconecting to ftp");
  await ftpConnect.downloadFileWithRetry(ftpArchiveFullPath, File(localArchiveFullPath), pRetryCount: 1);
}
```

**Comment by salim-lachdhaf** [comment]
sadly you can not. but even if you have that option it want help you. because in all cases you are forced to retry all connexion steps ...

**Comment by bubnenkoff** [comment]
And what you could suggest? To catch exception and call connection inside
it again?

Вс, 16 янв. 2022 г. в 04:18, Salim Lachdhaf ***@***.***>:

**Comment by salim-lachdhaf** [comment]
modify your FTP setting.

**Comment by bubnenkoff** [comment]
I can’t its external FTP…

Вс, 16 янв. 2022 г. в 16:42, Salim Lachdhaf ***@***.***>:
