### ISSUE TITLE
How to fix next Exception?

### ISSUE THREAD

**Issue by bubnenkoff** [salim-lachdhaf/ftpConnect#48]
I am getting Exception:
```
listDirectoryContent FTPException: FTPException: Timeout reached forUnhandled exception:
FTPException: Timeout reached for Receiving response ! (Response: nu#0      FTPSocket.readResponse.<anonymous closure> (package:ftpconne#1      _RootZone.run (dart:async/zone.dart:1681:54)
#2      Future.timeout.<anonymous closure> (dart:async/future_impl.d#3      Timer._createTimer.<anonymous closure> (dart:async-patch/tim#4      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:395:19#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isola
```

On this code:
```

await ftpConnect.changeDirectory(context.join(sectionPath));
  try {
      sectionEntries = await ftpConnect.listDirectoryContent(cmd: DIR_LIST_COMMAND.LIST).; 
  } on FTPException catch(e) { // try again
    print('listDirectoryContent FTPException: $e');
      sleep(Duration(seconds:1));
      sectionEntries = await ftpConnect.listDirectoryContent(cmd: DIR_LIST_COMMAND.LIST); 
  }
  for(var file in sectionEntries) { 
  ....
  }
```              

Could anybody suggest how to prevent app from crush?

**Comment by salim-lachdhaf** [comment]
put it in try catch either

**Comment by bubnenkoff** [comment]
@salim-lachdhaf second call:
```
sectionEntries = await ftpConnect.listDirectoryContent(cmd: DIR_LIST_COMMAND.LIST); 
```
?
