### ISSUE TITLE
error running the other functions

### ISSUE THREAD

**Issue by nicolasvahidzein** [salim-lachdhaf/ftpConnect#5]
Hello,

thank you for your great package.

when i run these examples:

```
	
	Future<List> listDirectoryContent() async{
		
		Map ftpSettings = _appRepository.retrieveFtpSettingsExport();
		
		FTPConnect ftpConnect = FTPConnect(ftpSettings['path'], user:ftpSettings['username'], pass:ftpSettings['password']);
		
		List<FTPEntry> directoryContent = await ftpConnect.listDirectoryContent();
		
		return directoryContent;
		
	}
	
	Future<String> getCurrentDirectory() async{
		
		Map ftpSettings = _appRepository.retrieveFtpSettingsExport();
		
		FTPConnect ftpConnect = FTPConnect(ftpSettings['path'], user:ftpSettings['username'], pass:ftpSettings['password']);
		
		String currentDirectory = await ftpConnect.currentDirectory();
		
		return currentDirectory;
		
	}
	
```

 i get an error:

```
D/ViewRootImpl@963fdfd[MainActivity]( 7893): ViewPostIme pointer 0
D/ViewRootImpl@963fdfd[MainActivity]( 7893): ViewPostIme pointer 1
[38;5;248mI/flutter ( 7893): _formSubmittedBis function inside process_incoming_packages_view.dart[39;49m
I/flutter ( 7893): Formatted: 1604197892229
[38;5;248mI/flutter ( 7893): retrieveFtpSettingsExport function inside app_repository.dart[39;49m
E/flutter ( 7893): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: NoSuchMethodError: The method 'write' was called on null.
E/flutter ( 7893): Receiver: null
E/flutter ( 7893): Tried calling: write(Uint8Array)
[38;5;244mE/flutter ( 7893): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)[39;49m
[38;5;248mE/flutter ( 7893): #1      FTPSocket.sendCommand[39;49m
 package:ftpconnect/src/ftpSocket.dart
[38;5;248mE/flutter ( 7893): #2      TransferUtil.setTransferMode[39;49m
 package:ftpconnect/…/util/transferUtil.dart
[38;5;248mE/flutter ( 7893): #3      FTPDirectory.listDirectoryContent[39;49m
 package:ftpconnect/…/commands/directory.dart
[38;5;248mE/flutter ( 7893): #4      FTPConnect.listDirectoryContent[39;49m
 package:ftpconnect/src/ftpclient_base.dart
[38;5;248mE/flutter ( 7893): #5      FtpOperations.listDirectoryContent[39;49m
 package:assetscan_client_mobile/utils/ftp_operations.dart
[38;5;248mE/flutter ( 7893): #6      _ProcessIncomingPackagesViewState._formSubmittedBis[39;49m
 package:assetscan_client_mobile/screens/process_incoming_packages_view.dart
E/flutter ( 7893): <asynchronous suspension>
[38;5;248mE/flutter ( 7893): #7      _ProcessIncomingPackagesViewState._formSubmitted.<anonymous closure>.<anonymous closure>[39;49m
 package:assetscan_client_mobile/screens/process_incoming_packages_view.dart
[38;5;244mE/flutter ( 7893): #8      _InkResponseState._handleTap[39;49m
 package:flutter/…/material/ink_well.dart
[38;5;244mE/flutter ( 7893): #9      _InkResponseState.build.<anonymous closure>[39;49m
 package:flutter/…/material/ink_well.dart
[38;5;244mE/flutter ( 7893): #10     GestureRecognizer.invokeCallback[39;49m
 package:flutter/…/gestures/recognizer.dart
[38;5;244mE/flutter ( 7893): #11     TapGestureRecognizer.handleTapUp[39;49m
 package:flutter/…/gestures/tap.dart
[38;5;244mE/flutter ( 7893): #12     BaseTapGestureRecognizer._checkUp[39;49m
 package:flutter/…/gestures/tap.dart
[38;5;244mE/flutter ( 7893): #13     BaseTapGestureRecognizer.handlePrimaryPointer[39;49m
 package:flutter/…/gestures/tap.dart
[38;5;244mE/flutter ( 7893): #14     PrimaryPointerGestureRecognizer.handleEvent[39;49m
 package:flutter/…/gestures/recognizer.dart
[38;5;244mE/flutter ( 7893): #15     PointerRouter._dispatch[39;49m
 package:flutter/…/gestures/pointer_router.dart
[38;5;244mE/flutter ( 7893): #16     PointerRouter._dispatchEventToRoutes.<anonymous closure>[39;49m
 package:flutter/…/gestures/pointer_router.dart
[38;5;244mE/flutter ( 7893): #17     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)[39;49m
[38;5;244mE/flutter ( 7893): #18     PointerRouter._dispatchEventToRoutes[39;49m
 package:flutter/…/gestures/pointer_router.dart
[38;5;244mE/flutter ( 7893): #19     PointerRouter.route[39;49m
 package:flutter/…/gestures/pointer_router.dart
[38;5;244mE/flutter ( 7893): #20     GestureBinding.handleEvent[39;49m
 package:flutter/…/gestures/binding.dart
[38;5;244mE/flutter ( 7893): #21     GestureBinding.dispatchEvent[39;49m
 package:flutter/…/gestures/binding.dart
[38;5;244mE/flutter ( 7893): #22     RendererBinding.dispatchEvent[39;49m
 package:flutter/…/rendering/binding.dart
[38;5;244mE/flutter ( 7893): #23     GestureBinding._handlePointerEvent[39;49m
 package:flutter/…/gestures/binding.dart
[38;5;244mE/flutter ( 7893): #24     GestureBinding._flushPointerEventQueue[39;49m
 package:flutter/…/gestures/binding.dart
[38;5;244mE/flutter ( 7893): #25     GestureBinding._handlePointerDataPacket[39;49m
 package:flutter/…/gestures/binding.dart
[38;5;244mE/flutter ( 7893): #26     _rootRunUnary (dart:async/zone.dart:1206:13)[39;49m
[38;5;244mE/flutter ( 7893): #27     _CustomZone.runUnary (dart:async/zone.dart:1100:19)[39;49m
[38;5;244mE/flutter ( 7893): #28     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)[39;49m
[38;5;244mE/flutter ( 7893): #29     _invoke1 (dart:ui/hooks.dart:265:10)[39;49m
[38;5;244mE/flutter ( 7893): #30     _dispatchPointerDataPacket (dart:ui/hooks.dart:174:5)[39;49m
E/flutter ( 7893):
I/flutter ( 7893): Tick {}
I/flutter ( 7893): tick event
I/flutter ( 7893): Tick {}
I/flutter ( 7893): tick event
I/flutter ( 7893): Tick {}
I/flutter ( 7893): tick event

```

**Comment by joannakotula** [comment]
I think I had similar problem. If you want to know more try adding 'debug: true' to your FTPConnect function.
