### ISSUE TITLE
 TransferUtil.retryAction.<anonymous closure> (package:ftpconnect/src/util/transferUtil.dart:68:11)

### ISSUE THREAD

**Issue by bubnenkoff** [salim-lachdhaf/ftpConnect#50]
I still can't find the place of random crush. Here is latest crash-log:
```
Unhandled exception:
Null check operator used on a null value
#0      TransferUtil.retryAction.<anonymous closure> (package:ftpconnect/src/util/transferUtil.dart:68:11)
<asynchronous suspension>
#1      _RootZone.bindUnaryCallbackGuarded.<anonymous closure> (dart:async/zone.dart)
<asynchronous suspension>
```

**Comment by salim-lachdhaf** [comment]
could you past your exception

**Comment by bubnenkoff** [comment]
I can't find place where this error happens. But it happens during file downloading somewhere here 
https://github.com/bubnenkoff/ftp_errror/blob/main/lib/Services/ftp_service.dart#L241

Latest what I am seeing on console is:
```
FTP remote path:  /fcs_regions/Voronezhskaja_obl/protocols/protocol_Voronezhskaja_obl_2016050100_2016060100_005.xml.zip
localArchiveFolder: D:\zak_data\fz44\protocols\Voronezhskaja_obl
local path: D:\zak_data\fz44\protocols\Voronezhskaja_obl\protocol_Voronezhskaja_obl_2016050100_2016060100_005.xml.zip
aa11
getListOfArchives. Root folder: /fcs_regions/
Unhandled exception:
Null check operator used on a null value
#0      TransferUtil.retryAction.<anonymous closure> (package:ftpconnect/src/util/transferUtil.dart:68:11)
<asynchronous suspension>
#1      _RootZone.bindUnaryCallbackGuarded.<anonymous closure> (dart:async/zone.dart)
<asynchronous suspension>
```

So `aa11` is printing, but `bb11` is not:
```
   print("aa11");
   await ftpConnect.downloadFileWithRetry(ftpArchiveFullPath, File(localArchiveFullPath), pRetryCount: 2);
   print("bb11");
```

**Comment by salim-lachdhaf** [comment]
first of all replace on FTPException with general `Exception(e)` to catch all errors and insure re download process.
second add `Future` before the function `downloadArchive`

**Comment by bubnenkoff** [comment]
@salim-lachdhaf you mean to do:
```
Future downloadArchive([isRestartedByException = false]) async {
```
instead of:
```
downloadArchive([isRestartedByException = false]) async {
```
?

Could you explain why do I need it? I thought it's not needed here.

> first of all replace on FTPException with general Exception(e)

Ok I will try it.

**Comment by bubnenkoff** [comment]
@salim-lachdhaf did not helped :( I had update code in git. The latest crash is:
```
FTP Exception! we will call downloadArchive again: FTPException: Remote File /fcs_regions/Khanty-Mansijskij_AO-Jugra_AO/protocols/protocol_Khanty-Mansijskij_AO-Jugra_AO_2016050100_2016060100_009.xml.zip does not exist! (Response: null) Second Attempt to download file
ftp.zakupki.gov.ru, free, free
---------
Unhandled exception:
Null check operator used on a null value
#0      FTPSocket.readResponse.<anonymous closure> (package:ftpconnect/src/ftpSocket.dart:30:21)
#1      FTPSocket.readResponse.<anonymous closure> (package:ftpconnect/src/ftpSocket.dart:26:26)
#2      Future.doWhile.<anonymous closure> (dart:async/future.dart:613:26)
#3      _RootZone.runUnaryGuarded (dart:async/zone.dart:1620:10)
#4      _RootZone.bindUnaryCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1659:26)
<asynchronous suspension>
#5      _RootZone.bindUnaryCallbackGuarded.<anonymous closure> (dart:async/zone.dart)
<asynchronous suspension>
```

**Comment by salim-lachdhaf** [comment]
i now exactly the issue, but it's weired it should not happen.
https://github.com/salim-lachdhaf/ftpConnect/blob/f064ead005702bac63b7f6698c21ef08b7a27212/lib/src/ftpSocket.dart#L30
just replace ! by ?, i will correct that.


however from your side try this options 1 by one:
1- delete retry option
2- enable log to track ftp state.

to summary, it seems when you call `ftpReconnect` sockt is set to null, but in mean time there a process in progress witch cause crash. and i think is the retry. so try to remove it.

**Comment by bubnenkoff** [comment]
Thanks i will try! How enable second option with logging ftp state?

Сб, 5 февр. 2022 г. в 01:14, Salim Lachdhaf ***@***.***>:

**Comment by bubnenkoff** [comment]
deleting retry option did not did not helped. 

Now I am trying to fix source code as you said. 
```
ftpconnect-1.0.1/lib/src/ftpSocket.dart:30:35: Error: Operator '>' cannot be called on 'int?' because it is potentially null.
      while (_socket?.available() > 0) {
```
Possible it should be:
```
while (_socket?.available() != null && _socket!.available() > 0) {
```
At last it's compiled. Run it, wait for the result.

**Comment by bubnenkoff** [comment]
![изображение](https://user-images.githubusercontent.com/6514326/152671594-857ccbde-456a-45a9-a5f3-dcdb085f5817.png)

**Comment by bubnenkoff** [comment]
@salim-lachdhaf if you have any ideas please give me know. The problem still actual for me.

**Comment by salim-lachdhaf** [comment]
give me a full example that has the issue to analyse it ...

**Comment by bubnenkoff** [comment]
@salim-lachdhaf 

PG table.sql - that need for starting it's working
py_test.py - for starting job 

https://github.com/bubnenkoff/ftp_errror/

Crush happens after 2-3 hours of working.

**Comment by bubnenkoff** [comment]
@salim-lachdhaf 
```
notification_Altajskij_kraj_2022010100_2022020100_004.xml.zip
notification_Altajskij_kraj_2022010100_2022020100_005.xml.zip
----------------------------
229 Entering Extended Passive Mode (|||33130|)

____________________________
startNewJob exception
FTPException: Timeout reached for Receiving response ! (Response: null)
startNewJob
Processing fz: fz44
ftp.zakupki.gov.ru, free, free
---------
Exeption in ftpReconnect: FTPException: Timeout reached for Receiving response ! (Response: null)
ftp.zakupki.gov.ru, free, free
---------
startNewJob exception
FTPException: Wrong password (Response: 221 Goodbye.
)
startNewJob
Processing fz: fz44
ftp.zakupki.gov.ru, free, free
---------
Exeption in ftpReconnect: Null check operator used on a null value
ftp.zakupki.gov.ru, free, free
---------
getListOfArchives. Root folder: /fcs_regions/
----------------------------
229 Entering Extended Passive Mode (|||30827|)

____________________________
2022-02-15 16:17:23.701823 - info - GET - /
startNewJob exception
FTPException: Timeout reached for Receiving response ! (Response: null)
startNewJob
Processing fz: fz44
ftp.zakupki.gov.ru, free, free
---------
startNewJob exception
FTPException: Timeout reached for Receiving response ! (Response: null)
startNewJob
Processing fz: fz44
ftp.zakupki.gov.ru, free, free
---------
Unhandled exception:
Null check operator used on a null value
#0      FTPSocket.sendCommand (package:ftpconnect/src/ftpSocket.dart:51:12)
#1      FTPSocket.connect (package:ftpconnect/src/ftpSocket.dart:99:23)
<asynchronous suspension>
#2      startNewJob (package:data_loader/Services/ftp_service.dart:836:9)
<asynchronous suspension>
```

**Comment by salim-lachdhaf** [comment]
well it the same error but each time in different places, `_socket` is null .
the only place that we setted `_socket` =null is in `disconnect` function.

my next advice is to not use your `reConnect` , **DON't disconnect** , and see what it gives. use only connect, i think you are missing a `wait` somewhere.
and increase `timeOut` either.

**Comment by salim-lachdhaf** [comment]
prevent using recursive function in your code to prevent looping in infinit error.
modify your function like this 
```
downloadArchive(int nbMaxretry){
if(nbMaxretry > MYMAX){
    return;
}
    .
    .
    .
    .
    
    
    
    downloadArchive(nbMaxretry+1);
}
```

**Comment by bubnenkoff** [comment]
@salim-lachdhaf I did not understand this part:
"my next advice is to not use your reConnect , DON't disconnect , and see what it gives. use only connect, i think you are missing a wait somewhere."

You mean to try to comment disconnect part?
```
ftpReconnect() async {
    try {
      //  await ftpConnect.disconnect();
      //  ftpConnect = getFTPConnection();
        await ftpConnect.connect();
      } catch (e) {
        print('Exeption in ftpReconnect: $e');
        sleep(Duration(seconds: 1));
        ftpReconnect();
      }
          
}
```
?

**Comment by salim-lachdhaf** [comment]
yes, and add `Future` keyword like this `Future ftpReconnect() async`  ( it could be the source of problem ) and remove recursivity here either, it could create zn infinite loop

**Comment by bubnenkoff** [comment]
I am continue experiments. I tried to comment disconnect:
```
ftpReconnect() async {
    try {
    //    await ftpConnect.disconnect();
        ftpConnect = getFTPConnection();
        await ftpConnect.connect();
      } catch (e) {
        print('Exeption in ftpReconnect: $e');
        sleep(Duration(seconds: 1));
        ftpReconnect();
      }
}
```
result:

```
getListOfArchives. Root folder: /fcs_regions/
Exeption in ftpReconnect: FTPException: Timeout reached for Receiving response ! (Response: null)
ftp.zakupki.gov.ru, free, free
---------
Unhandled exception:
Null check operator used on a null value
#0      FTPSocket.sendCommand (package:ftpconnect/src/ftpSocket.dart:51:12)
#1      TransferUtil.setTransferMode (package:ftpconnect/src/util/transferUtil.dart:14:23)
#2      FTPSocket.setTransferMode (package:ftpconnect/src/ftpSocket.dart:111:26)
#3      FTPDirectory.listDirectoryContent (package:ftpconnect/src/commands/directory.dart:53:19)
#4      FTPConnect.listDirectoryContent (package:ftpconnect/src/ftpclient_base.dart:149:10)
#5      getListOfArchives (package:data_loader/Services/ftp_service.dart:44:37)
<asynchronous suspension>
#6      getListOfArchives (package:data_loader/Services/ftp_service.dart:39:5)
<asynchronous suspension>
#7      saveArchivesToDB (package:data_loader/Services/ftp_service.dart:138:19)
<asynchronous suspension>
#8      runFtpParsingOrOnlyUnpackArchives (package:data_loader/Services/ftp_service.dart:812:5)
<asynchronous suspension>
#9      choiceOfProcessingAction (package:data_loader/Services/ftp_service.dart:735:13)
<asynchronous suspension>
#10     startNewJob (package:data_loader/Services/ftp_service.dart:840:9)
<asynchronous suspension>
```

**Comment by bubnenkoff** [comment]
@salim-lachdhaf 

code:
```
Future ftpReconnect() async {
    try {
    //    await ftpConnect.disconnect();
        ftpConnect = getFTPConnection();
        await ftpConnect.connect();
      } catch (e) {
        print('Exeption in ftpReconnect: $e');
        sleep(Duration(seconds: 1));
        await ftpReconnect();
      }
          
}
```
and error:
```
startNewJob exception
FTPException: Timeout reached for Receiving response ! (Response: null)
startNewJob
Processing fz: fz44
ftp.zakupki.gov.ru, free, free
---------
Exeption in ftpReconnect: FTPException: Timeout reached for Receiving response ! (Response: null)
ftp.zakupki.gov.ru, free, free
---------
Unprocessed XML Count: 208
NOT ENOUGH files: 208 while needed at least 65000. Running!
runFtpParsingOrOnlyUnpackArchives
First run of data-loader
saveArchivesToDB
getListOfArchives. Root folder: /fcs_regions/
Unhandled exception:
Null check operator used on a null value
#0      FTPSocket.sendCommand (package:ftpconnect/src/ftpSocket.dart:51:12)
#1      FTPDirectory.changeDirectory (package:ftpconnect/src/commands/directory.dart:31:39)
#2      FTPConnect.changeDirectory (package:ftpconnect/src/ftpclient_base.dart:133:34)
#3      getListOfArchives (package:data_loader/Services/ftp_service.dart:34:22)
#4      saveArchivesToDB (package:data_loader/Services/ftp_service.dart:136:25)
#5      runFtpParsingOrOnlyUnpackArchives (package:data_loader/Services/ftp_service.dart:812:11)
#6      choiceOfProcessingAction (package:data_loader/Services/ftp_service.dart:735:19)
<asynchronous suspension>
#7      runFtpParsingOrOnlyUnpackArchives (package:data_loader/Services/ftp_service.dart:805:9)
<asynchronous suspension>
#8      choiceOfProcessingAction (package:data_loader/Services/ftp_service.dart:735:13)
<asynchronous suspension>
#9      startNewJob (package:data_loader/Services/ftp_service.dart:840:9)
<asynchronous suspension>
#10     main.<anonymous closure> (file:///D:/code/zakupki/data_loader/bin/data_loader.dart:46:8)
<asynchronous suspension>
```

**Comment by salim-lachdhaf** [comment]
it seems that you are not connected to the ftp at all, and each time you receive timeout.

try increase the `timeout` proporties in `ftpConnect` and make sure that you are using the correct protocols (secured or not)

**Comment by salim-lachdhaf** [comment]
not connected mean `_socket` `=null,` for this you get all this null error.
you can uncomment the disconnect function it's not the cause.

your problem is connecting to the FTP.
the second problem is that you try to make some operation like downloadFile but you are not connected (socket =null).

as solution, try find out why you cannot connect, maybe your server allows only one connexion ....

step two, if the connexion ftp fails you should not call other ftp function. you have to organise your code structure.
